language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=mysql
  - DB=postgres
before_install:
  - "sudo apt-get install -qq libsndfile-dev"
before_script:
  - "mysql -e 'create database social_stream_test;'"
  - "psql -c 'create database social_stream_test;' -U postgres"

# blacklist
branches:
  except:
    - staging
