source "http://rubygems.org"

# Uncomment the following lines if you are planing to
# use a local code of mailboxer or avatar_for_rails gems
#
gem 'mailboxer', :git => 'git://github.com/malagoli/mailboxer.git' #:path => '/home/davide/sources/mailboxer' #:git => 'git://github.com/malagoli/mailboxer.git' #,     #:git => 'git://github.com/malagoli/ma$

# gem 'social_cheesecake', :path => '../../SocialCheesecake/social_cheesecake'
# gem 'avatars_for_rails', :path => '../avatars_for_rails'

gemspec
